# config.yaml
reference: "/data1/greenbab/database/mm10/mm10.fa"
outdir: "gatk_CollectAlignmentSummaryMetrics"
picard_container: "/data1/greenbab/users/ahunos/apps/containers/gatk.sif"
mm10_chrSizes: /data1/greenbab/database/mm10/mm10.chrom.sizes