samples:
    D-0-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/snps_longphase_modcalls/s4000/sandbox/results/results/longphase_haplotag/D-0-2_4000/D-0-2_4000_haplotagged.bam
    D-0-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/snps_longphase_modcalls/s4000/sandbox/results/results/longphase_haplotag/D-0-1_4000/D-0-1_4000_haplotagged.bam
